from __future__ import annotations

import json
import os
import sys
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Literal

import anyio
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, field_validator

from medical_coder_llm.config.models import _DEFAULT_OPENAI_BASE, is_openai_cloud_base
from medical_coder_llm.run_code import run_coding_to_json

STATIC_DIR = Path(__file__).resolve().parent / "static"

_DOTENV_MANAGED_KEYS = (
    "MODEL_PROVIDER",
    "MODEL_NAME",
    "GEMINI_API_KEY",
    "OPENAI_API_KEY",
    "OPEN_AI_URL",
)


def _cwd_dotenv_path() -> Path:
    return Path.cwd() / ".env"


def _format_dotenv_value(val: str) -> str:
    if "\n" in val or "\r" in val:
        raise HTTPException(
            status_code=400,
            detail="Configuration values must not contain newline characters.",
        )
    if val == "":
        return ""
    safe = not any(c in val for c in "#= \"'\t\\") and val.strip() == val
    if safe:
        return val
    escaped = val.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _build_dotenv_lines(
    *,
    provider: Literal["gemini", "openai"],
    model_name: str,
    gemini_api_key: str,
    openai_api_key: str,
    open_ai_url: str,
) -> str:
    lines = [
        "# Medical Coder — generated by web setup",
        f"MODEL_PROVIDER={_format_dotenv_value(provider)}",
        f"MODEL_NAME={_format_dotenv_value(model_name)}",
    ]
    if provider == "gemini":
        lines.append(f"GEMINI_API_KEY={_format_dotenv_value(gemini_api_key)}")
    else:
        url = open_ai_url.strip().rstrip("/")
        if url:
            lines.append(f"OPEN_AI_URL={_format_dotenv_value(url)}")
        lines.append(f"OPENAI_API_KEY={_format_dotenv_value(openai_api_key)}")
    return "\n".join(lines) + "\n"


@asynccontextmanager
async def lifespan(_app: FastAPI):
    load_dotenv()
    yield


app = FastAPI(title="Medical Coder LLM", version="0.2.3", lifespan=lifespan)

if STATIC_DIR.is_dir():
    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


class CodeRequest(BaseModel):
    note: str = Field(..., description="Clinical note text")
    ontology: str = "data/ontology/codes.csv"

    @field_validator("ontology", mode="before")
    @classmethod
    def empty_str_to_default(cls, v: object) -> object:
        if v == "":
            return "data/ontology/codes.csv"
        return v


class SetupRequest(BaseModel):
    model_provider: Literal["gemini", "openai"]
    model_name: str = Field(..., min_length=1)
    open_ai_url: str = ""
    openai_api_key: str = ""
    gemini_api_key: str = ""
    overwrite: bool = False

    @field_validator("model_name", mode="before")
    @classmethod
    def strip_model_name(cls, v: object) -> object:
        if isinstance(v, str):
            return v.strip()
        return v

    @field_validator("model_name")
    @classmethod
    def non_empty_model_name(cls, v: str) -> str:
        if not v:
            raise ValueError("model_name must not be empty")
        return v


@app.get("/api/setup-status")
def setup_status() -> dict[str, bool]:
    path = _cwd_dotenv_path()
    present = path.is_file()
    return {"needsSetup": not present, "dotenvPresent": present}


@app.delete("/api/setup")
def api_setup_clear() -> dict[str, bool]:
    path = _cwd_dotenv_path()
    if path.is_file():
        try:
            path.unlink()
        except OSError as e:
            raise HTTPException(
                status_code=500,
                detail=f"Could not remove `.env`: {e}",
            ) from e
    for key in _DOTENV_MANAGED_KEYS:
        os.environ.pop(key, None)
    return {"ok": True, "needsSetup": not _cwd_dotenv_path().is_file()}


@app.post("/api/setup")
def api_setup(body: SetupRequest) -> dict[str, bool]:
    path = _cwd_dotenv_path()
    if path.exists() and not body.overwrite:
        raise HTTPException(
            status_code=409,
            detail=(
                "A `.env` file already exists. Open “Change LLM settings” in the browser "
                "to replace it, send `overwrite: true` in the JSON body, or delete `.env` first."
            ),
        )

    provider = body.model_provider
    model_name = body.model_name
    open_ai_url = body.open_ai_url.strip()
    openai_key = body.openai_api_key.strip()
    gemini_key = body.gemini_api_key.strip()

    if provider == "gemini":
        if not gemini_key:
            raise HTTPException(
                status_code=400,
                detail="API key is required for Gemini.",
            )
    else:
        resolved_base = (
            open_ai_url.rstrip("/")
            if open_ai_url
            else _DEFAULT_OPENAI_BASE.rstrip("/")
        )
        if is_openai_cloud_base(resolved_base) and not openai_key:
            raise HTTPException(
                status_code=400,
                detail="API key is required for OpenAI cloud.",
            )

    content = _build_dotenv_lines(
        provider=provider,
        model_name=model_name,
        gemini_api_key=gemini_key,
        openai_api_key=openai_key,
        open_ai_url=open_ai_url,
    )

    try:
        path.write_text(content, encoding="utf-8")
    except OSError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Could not write `.env` in the current directory: {e}",
        ) from e

    if sys.platform != "win32":
        try:
            path.chmod(0o600)
        except OSError:
            pass

    os.environ["MODEL_PROVIDER"] = provider
    os.environ["MODEL_NAME"] = model_name
    if provider == "gemini":
        os.environ["GEMINI_API_KEY"] = gemini_key
        os.environ.pop("OPENAI_API_KEY", None)
        os.environ.pop("OPEN_AI_URL", None)
    else:
        os.environ["OPENAI_API_KEY"] = openai_key
        if open_ai_url:
            os.environ["OPEN_AI_URL"] = open_ai_url.rstrip("/")
        else:
            os.environ.pop("OPEN_AI_URL", None)
        os.environ.pop("GEMINI_API_KEY", None)

    load_dotenv(dotenv_path=path, override=True)

    return {"ok": True}


@app.get("/")
def index() -> FileResponse:
    index_path = STATIC_DIR / "index.html"
    if not index_path.is_file():
        raise HTTPException(status_code=500, detail="Web UI files are missing.")
    return FileResponse(index_path)


@app.post("/api/code")
async def api_code(body: CodeRequest) -> dict[str, object]:
    def _run() -> str:
        return run_coding_to_json(
            body.note,
            ontology_path=body.ontology,
        )

    try:
        raw = await anyio.to_thread.run_sync(_run)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e

    return json.loads(raw)
